# Usando a imagem oficial do PostgreSQL 17
FROM postgres:17

# Definindo variáveis de ambiente
ENV POSTGRES_DB=api_pedidos
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# Expondo a porta padrão do PostgreSQL
EXPOSE 5432